usbip: fix compile on platforms with VFP
fix VFP/no VFP due to missing CFLAGS
add CFLAGS to Makefile.am

remove -Werror in configure.ac
fix error:
usbip_network.c: In function 'usbip_net_tcp_connect':
usbip_network.c:264:6: error: 'sockfd' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  int sockfd;
      ^
cc1: all warnings being treated as errors

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>