[packages] remotefs: update to fix gcc 4.8 issues
update to current git fixes:
src/md5crypt/md5.c: In function 'MD5Final':
src/md5crypt/md5.c:163:26: error: argument to 'sizeof' in 'memset' [...]

according to remotefs git commit log:
id 28c8b9c505ebef467b329533d7416255425a5020
id 96dc4891fedb40eb3f016c796e8d39b6d81803a5
+fixed md5.c for gcc 4.7

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>