libowfat: update to libowfat 0.29
new release fixes a compile error:
socket/socket_remote4.c:11:23: fatal error: havescope.h: No such file or directory

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>