libdmapsharing: prevent dpapview build
dpapview depends on gtk
leading to build error:
dpapview.c:29:21: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>

http://patchwork.openwrt.org/patch/4892/

Signed-off-by: Michel Stempin <michel.stempin@wanadoo.fr>
Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>