input-utils: update to 1.1
- change upstream URL
- update to 1.1 release
- delete obsolete patches (they are in upstream)

patch 001
- fix compile on sys with sh->dash (Debian,Ubuntu)
Error:
Make.config:1: *** empty variable name.  Stop.
Reason: echo -e in mk/Autoconf.mk

patch 002:
- use the target Linux headers from environment (INPUT)
Error depending on Kernel:
In file included from input.c:48:0:
KEY.h:243:4: error: 'KEY_WWAN' undeclared here (not in a function)
  [ KEY_WWAN         ] = "WWAN",

fixes https://dev.openwrt.org/ticket/14028

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>