[package] zaptel-1.4.x : mark as broken
zeptel-1.4.x is deprecated since 2008
it's DAHDI now

Kernel 3.10 removed create_proc_read_entry()
compile error:
zaptel-base.c:5253:4: error: implicit declaration of function 'create_proc_read_entry'
[-Werror=implicit-function-declaration]

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>