libxslt: update to 1.1.28
fixes build error in 1.1.26:
xsltutils.c: In function 'xsltSaveResultToString':
xsltutils.c:1758:26: error: dereferencing pointer to incomplete type
  *doc_txt_len = buf->conv->use;

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>