[packages] tesseract: fix gcc 4.8 compile
unistd.h missing

error:
svutil.cpp:89:18: error: 'fork' was not declared in this scope
   int pid = fork();
                  ^
svutil.cpp:119:28: error: 'execvp' was not declared in this scope
     execvp(executable, argv);
                            ^
svutil.cpp: In member function 'void SVNetwork::Close()':
svutil.cpp:262:16: error: 'close' was not declared in this scope
   close(stream_);
                ^
svutil.cpp: In constructor 'SVNetwork::SVNetwork(const char*, int)':
svutil.cpp:417:14: error: 'sleep' was not declared in this scope
       sleep(1);

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>