shairport: fix build errors
- fix build error reported by build bots
 undefined reference to `pa_simple_free'

libs was missing libpulse-simple and libpulse

-rpath-link fixes build error:
ld: warning: libpulsecommon-5.0.so, needed by libpulse-simple.so,
not found (try using -rpath or -rpath-link)

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>