ccid: update to ccid 1.4.15
add -lpthread to TARGET_LDFLAGS fixes
parse-ccid_usb.o: undefined reference to symbol 'pthread_create'
'pthread_create' is defined in DSO .../libpthread.so.0 so try adding it to the linker command line
libpthread.so.0: could not read symbols: Invalid operation

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>