gnutls: fix build error on x86/x86-64
build error was caused by overwriting AM_CFLAGS
but AM_CFLAGS carries flags for hardware acceleration

fixes https://dev.openwrt.org/ticket/15555
Error was:
sha-padlock.c:355:49: error: 'sha1' undeclared here (not in a function)
 const struct nettle_hash padlock_sha1 = NN_HASH(sha1, padlock_sha1_update, padlock_sha1_digest, SHA1);

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>