[packages] lame: fix compile error on gcc 4.9.0
gcc 4.9.0 complains because it uses SSE instructions
when no SSE support is available
lame does not use USE_SSE like other projects
so simply including xmmintrin.h fails with build errors like

xmm_quantize_sub.c: In function 'init_xrpow_core_sse':
xmm_quantize_sub.c:55:18: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
     const __m128 vec_fabs_mask = _mm_loadu_ps((float const*) &fabs_mask[0]);

include/xmmintrin.h:929:1: error: inlining failed in call to always_inline '_mm_loadu_ps': target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^

so deactivate xmmintrin.h on i386

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>